### ISSUE TITLE
人脸录入中时间阈值问题

### ISSUE THREAD

**Issue by kmq132** [littleseven2003/FaceRecognitionSystem#17]
人脸录入中没有类似人脸识别功能中，超过20s自动取消的功能，可能会一直卡住

**Comment by littleseven2003** [comment]
@Chenqix 测试下你有没有这个问题，树莓派上有没有这个问题

**Comment by Chenqix** [comment]
@littleseven2003 有这个问题，会一直处于拍照中的状态

**Comment by littleseven2003** [comment]
## 问题原因：
没有给人脸录入的部分设置时间限制
## 解决方法：
增加录入时的时间限制，具体值可以由config文件中设置，超时会弹窗并结束录入

**Comment by littleseven2003** [comment]
修改已经push到debug-code-standard分支，请更新代码并查看问题是否解决
