### ISSUE TITLE
数据管理中名字不能正确录入

### ISSUE THREAD

**Issue by kmq132** [littleseven2003/FaceRecognitionSystem#18]
如果在人脸录入中输入类似“00_00”包含下划线的名字，在数据管理中只会显示如“00”这样第一个下划线之前的字符

**Comment by littleseven2003** [comment]
## 问题原因：
在录入和读取数据信息的时候是以下划线区分姓名和学号，如果姓名中含有下划线则会导致出现录入和读取的错误
## 解决方法：
设置姓名中含有下划线不合法并在输入检查的时候检查姓名中是否含有下划线。

修改已经push到debug-code-standard分支，请注意检查并更新代码，查看问题是否解决。
