### ISSUE TITLE
无数据时人脸识别

### ISSUE THREAD

**Issue by kmq132** [littleseven2003/FaceRecognitionSystem#21]
建议增加一个对是否有数据的判断，若数据管理中没有数据时点击人脸识别，会出现相应提示并取消该次识别

**Comment by littleseven2003** [comment]
## 问题原因：
代码中没有在识别之前对数据文件夹是否为空的检测。
## 解决方法：
添加检测，若识别之前检测到数据文件夹中没有人脸数据，则弹出警告弹窗并结束识别。
```
if data_manager.Data_Num == 0:
    msgbox.warning(self, "暂无人脸数据")
    return
```

修改已经push到debug-code-standard分支，请更新代码并检查问题是否解决。

**Comment by kmq132** [comment]
当data中只存在_tmp_img_时，会错误地将数据文件夹识别为非空，无法弹出警告弹窗并结束识别。

**Comment by littleseven2003** [comment]
## 问题原因：
在更新.data文件时会把因为错误滞留的"_tmp_img_"当做一个子文件夹进行处理
## 解决方法：
在更新.data文件之前先检查是否存在"_tmp_img_"文件夹，有则删除

**Comment by littleseven2003** [comment]
修改已经push到debug-code-standard分支，请更新代码并检查问题是否解决。
