### ISSUE TITLE
录入时问题

### ISSUE THREAD

**Issue by Chenqix** [littleseven2003/FaceRecognitionSystem#22]
录完人脸后，不能取消这一次操作，必须要填写姓名以及学号

**Comment by littleseven2003** [comment]
## 问题原因：
在录入界面没有设置取消的按钮。
## 解决方法：
在Qt设计中增加取消按钮，并添加信号槽点击那牛关闭页面。

**Comment by littleseven2003** [comment]
修改已经push到debug-code-standard当中，请更新代码并检查问题是否解决

**Comment by Chenqix** [comment]
已修复

**Comment by Chenqix** [comment]
已修复
