### ISSUE TITLE
删除数据

### ISSUE THREAD

**Issue by Chenqix** [littleseven2003/FaceRecognitionSystem#23]
删除数据后，显示框姓名与学号仍旧有显示，需要重新返回之后在进入才会消失

**Comment by littleseven2003** [comment]
## 问题原因：
在删除数据后，只刷新了表格，没有清空idEdit和nameEdit
## 解决方法：
在删除数据后清空idEdit和nameEdit
```python
self.idEdit.clear()
self.nameEdit.clear()
```

**Comment by littleseven2003** [comment]
修改已经push到debug-code-standard分支，请更新代码并检查问题是否解决

**Comment by Chenqix** [comment]
已修复
